### ISSUE TITLE
[meta] Items required for first release

### ISSUE THREAD

**Issue by LewisGaul** [richcooper95/crisis#7]
- [ ] UI for adding coaches
- [ ] plumbing between UI and backend
- [ ] DB set up on AWS and plumbed in to backend
- [ ] server running on AWS
- [ ] coach-assignment algorithm

**Comment by richcooper95** [comment]
Added 'general architecture review' to the list. Would be good to tick off any low-hanging fruit pre-first release.

**Comment by LewisGaul** [comment]
Update:
- New plan is to use AWS serverless (Lambda + DynamoDB + API Gateway + S3 + Cognito), which all needs setting up (replacing current DB implementation).
- There is some plumbing from frontend to backend, but currently hardcodes the development server, so needs fixing for production server.
